erDiagram
    PAYMENT {
        bigint id PK
        datetime created_at
        datetime updated_at
        varchar order_id
        varchar payment_id
        varchar refund_id
        varchar status
        double amount
        varchar currency
        varchar invoice_number
    }